name = "blockAlloy";
material = "iron";
stepSound = "metal";
creativeTab = "buildingBlocks";

addToCreative[0] = true;
hardness[0] = 3.0;
toolClass[0] = "pickaxe";
harvestLevel[0] = 2;
drop[0] = "Creator:blockAlloy:0 1"
textureFileXP[0] = "electricalSteelBlock.png";
textureFileXN[0] = "electricalSteelBlock.png";
textureFileYP[0] = "electricalSteelBlock.png";
textureFileYN[0] = "electricalSteelBlock.png";
textureFileZP[0] = "electricalSteelBlock.png";
textureFileZN[0] = "electricalSteelBlock.png";

addToCreative[1] = true;
hardness[1] = 3.0;
toolClass[1] = "pickaxe";
harvestLevel[1] = 2;
drop[1] = "Creator:blockAlloy:1 1"
textureFileXP[1] = "energeticAlloyBlock.png";
textureFileXN[1] = "energeticAlloyBlock.png";
textureFileYP[1] = "energeticAlloyBlock.png";
textureFileYN[1] = "energeticAlloyBlock.png";
textureFileZP[1] = "energeticAlloyBlock.png";
textureFileZN[1] = "energeticAlloyBlock.png";

addToCreative[2] = true;
hardness[2] = 3.0;
toolClass[2] = "pickaxe";
harvestLevel[2] = 2;
drop[2] = "Creator:blockAlloy:2 1"
textureFileXP[2] = "phasedGoldBlock.png";
textureFileXN[2] = "phasedGoldBlock.png";
textureFileYP[2] = "phasedGoldBlock.png";
textureFileYN[2] = "phasedGoldBlock.png";
textureFileZP[2] = "phasedGoldBlock.png";
textureFileZN[2] = "phasedGoldBlock.png";

addToCreative[3] = true;
hardness[3] = 3.0;
toolClass[3] = "pickaxe";
harvestLevel[3] = 2;
drop[3] = "Creator:blockAlloy:3 1"
textureFileXP[3] = "darkSteelBlock.png";
textureFileXN[3] = "darkSteelBlock.png";
textureFileYP[3] = "darkSteelBlock.png";
textureFileYN[3] = "darkSteelBlock.png";
textureFileZP[3] = "darkSteelBlock.png";
textureFileZN[3] = "darkSteelBlock.png";

addToCreative[4] = true;
hardness[4] = 3.0;
toolClass[4] = "pickaxe";
harvestLevel[4] = 2;
drop[4] = "Creator:blockAlloy:4 1"
textureFileXP[4] = "soulariumBlock.png";
textureFileXN[4] = "soulariumBlock.png";
textureFileYP[4] = "soulariumBlock.png";
textureFileYN[4] = "soulariumBlock.png";
textureFileZP[4] = "soulariumBlock.png";
textureFileZN[4] = "soulariumBlock.png";

addToCreative[5] = true;
hardness[5] = 3.0;
toolClass[5] = "pickaxe";
harvestLevel[5] = 2;
drop[5] = "Creator:blockAlloy:5 1"
textureFileXP[5] = "infuscolium_block.png";
textureFileXN[5] = "infuscolium_block.png";
textureFileYP[5] = "infuscolium_block.png";
textureFileYN[5] = "infuscolium_block.png";
textureFileZP[5] = "infuscolium_block.png";
textureFileZN[5] = "infuscolium_block.png";

addToCreative[6] = true;
hardness[6] = 3.0;
toolClass[6] = "pickaxe";
harvestLevel[6] = 2;
drop[6] = "Creator:blockAlloy:6 1"
textureFileXP[6] = "atlarus_block.png";
textureFileXN[6] = "atlarus_block.png";
textureFileYP[6] = "atlarus_block.png";
textureFileYN[6] = "atlarus_block.png";
textureFileZP[6] = "atlarus_block.png";
textureFileZN[6] = "atlarus_block.png";

addToCreative[7] = true;
hardness[7] = 3.0;
toolClass[7] = "pickaxe";
harvestLevel[7] = 2;
drop[7] = "Creator:blockAlloy:7 1"
textureFileXP[7] = "quicksilver_block.png";
textureFileXN[7] = "quicksilver_block.png";
textureFileYP[7] = "quicksilver_block.png";
textureFileYN[7] = "quicksilver_block.png";
textureFileZP[7] = "quicksilver_block.png";
textureFileZN[7] = "quicksilver_block.png";

addToCreative[8] = true;
hardness[8] = 3.0;
toolClass[8] = "pickaxe";
harvestLevel[8] = 2;
drop[8] = "Creator:blockAlloy:8 1"
textureFileXP[8] = "desichalkos_block.png";
textureFileXN[8] = "desichalkos_block.png";
textureFileYP[8] = "desichalkos_block.png";
textureFileYN[8] = "desichalkos_block.png";
textureFileZP[8] = "desichalkos_block.png";
textureFileZN[8] = "desichalkos_block.png";

addToCreative[9] = true;
hardness[9] = 3.0;
toolClass[9] = "pickaxe";
harvestLevel[9] = 2;
drop[9] = "Creator:blockAlloy:9 1"
textureFileXP[9] = "amordrine_block.png";
textureFileXN[9] = "amordrine_block.png";
textureFileYP[9] = "amordrine_block.png";
textureFileYN[9] = "amordrine_block.png";
textureFileZP[9] = "amordrine_block.png";
textureFileZN[9] = "amordrine_block.png";

addToCreative[10] = true;
hardness[10] = 3.0;
toolClass[10] = "pickaxe";
harvestLevel[10] = 2;
drop[10] = "Creator:blockAlloy:10 1"
textureFileXP[10] = "alduorite_block.png";
textureFileXN[10] = "alduorite_block.png";
textureFileYP[10] = "alduorite_block.png";
textureFileYN[10] = "alduorite_block.png";
textureFileZP[10] = "alduorite_block.png";
textureFileZN[10] = "alduorite_block.png";

addToCreative[11] = true;
hardness[11] = 3.0;
toolClass[11] = "pickaxe";
harvestLevel[11] = 2;
drop[11] = "Creator:blockAlloy:11 1"
textureFileXP[11] = "ceruclase_block.png";
textureFileXN[11] = "ceruclase_block.png";
textureFileYP[11] = "ceruclase_block.png";
textureFileYN[11] = "ceruclase_block.png";
textureFileZP[11] = "ceruclase_block.png";
textureFileZN[11] = "ceruclase_block.png";

addToCreative[12] = true;
hardness[12] = 3.0;
toolClass[12] = "pickaxe";
harvestLevel[12] = 2;
drop[12] = "Creator:blockAlloy:12 1"
textureFileXP[12] = "inolashite_block.png";
textureFileXN[12] = "inolashite_block.png";
textureFileYP[12] = "inolashite_block.png";
textureFileYN[12] = "inolashite_block.png";
textureFileZP[12] = "inolashite_block.png";
textureFileZN[12] = "inolashite_block.png";